package com.inovationware.toolkit.features.cycles.model.value;

import com.inovationware.toolkit.features.cycles.model.domain.Period;

public class Business {

    public String constructDetails(Period period){
        if (period == Period.First) return first;
        if (period == Period.Second) return second;
        if (period == Period.Third) return third;
        if (period == Period.Fourth) return fourth;
        if (period == Period.Fifth) return fifth;
        if (period == Period.Sixth) return sixth;
        if (period == Period.Seventh) return seventh;
        throw new RuntimeException("Invalid period!");
    }
    public String constructDetailsInYoruba(Period period){
        if (period == Period.First) return firstInYoruba;
        if (period == Period.Second) return secondInYoruba;
        if (period == Period.Third) return thirdInYoruba;
        if (period == Period.Fourth) return fourthInYoruba;
        if (period == Period.Fifth) return fifthInYoruba;
        if (period == Period.Sixth) return sixthInYoruba;
        if (period == Period.Seventh) return seventhInYoruba;
        throw new RuntimeException("Invalid period!");
    }
    public String constructDetailsInBulgarian(Period period){
        if (period == Period.First) return firstInBulgarian;
        if (period == Period.Second) return secondInBulgarian;
        if (period == Period.Third) return thirdInBulgarian;
        if (period == Period.Fourth) return fourthInBulgarian;
        if (period == Period.Fifth) return fifthInBulgarian;
        if (period == Period.Sixth) return sixthInBulgarian;
        if (period == Period.Seventh) return seventhInBulgarian;
        throw new RuntimeException("Invalid period!");
    }

    private final String first = "During the first fifty-two days of the yearly cycle of each business, beginning with its birthday and covering the fifty-two days following, each business will find greater success in all forms of promotion that solicit or depend for their success upon the good will and the preferment of the public. It is not as excellent a period for the actual building up of sales and return of money as it is a period for securing approval, favor, recognition, and general good will. This would be the period to solicit endorsements or high recognition by eminent persons and concerns that would either result eventually in sales through such persons, or in giving widespread publicity and advertising to the concern. It is also an excellent period in which to advertise a business widely, not so much for direct sales as to build up prestige and public recognition. It is a good period for the sending forth of emissaries, representatives, or high members of the firm to meet other eminent persons in the business world and, therefore, secure recognition and high favor. For this reason it is an excellent period to deal with government officials, judges of the court, or senators, or congressmen from whom you desire preferment, special favors or the passage of protective bills or regulations. This makes the period also good for the securing of political influence, political cooperation, and recognition. The thought of the concern during this period should be not of money, but of name, reputation, and prestige.\n";

    private final String firstInYoruba = "Ni awọn ọjọ mejilelọgọta akọkọ ti iyipo ọdọọdun ti iṣowo kọọkan, bẹrẹ pẹlu ọjọ-ibi rẹ ati ti o bo ọjọ mejilelaadọta ti o tẹle, iṣowo kọọkan yoo rii aṣeyọri nla ni gbogbo iru igbega ti o beere tabi gbarale aṣeyọri wọn lori ifẹ rere. ati awọn ààyò ti awọn àkọsílẹ. Kii ṣe akoko ti o dara julọ fun iṣelọpọ gidi ti tita ati ipadabọ owo bi o ṣe jẹ akoko fun ifipamo ifọwọsi, ojurere, idanimọ, ati ifẹ ti o dara gbogbogbo. Eyi yoo jẹ akoko lati beere awọn ifọwọsi tabi idanimọ giga nipasẹ awọn eniyan olokiki ati awọn ifiyesi ti yoo jẹ abajade nikẹhin ni tita nipasẹ iru awọn eniyan bẹẹ, tabi ni fifun ikede ati ipolowo kaakiri si ibakcdun naa. O tun jẹ akoko ti o tayọ ninu eyiti lati polowo iṣowo kan ni ibigbogbo, kii ṣe pupọ fun awọn tita taara lati kọ ọlá ati idanimọ gbogbo eniyan. O jẹ akoko ti o dara fun fifiranṣẹ awọn ikọṣẹ, awọn aṣoju, tabi awọn ọmọ ẹgbẹ giga ti ile-iṣẹ lati pade awọn eniyan olokiki miiran ni agbaye iṣowo ati, nitorinaa, idanimọ to ni aabo ati ojurere giga. Fun idi eyi o jẹ akoko ti o dara julọ lati ba awọn oṣiṣẹ ijọba, awọn onidajọ ile-ẹjọ, tabi awọn aṣofin agba, tabi awọn aṣofin lati ọdọ ẹniti o fẹ ayanfẹ, awọn ojurere pataki tabi gbigbe awọn owo aabo tabi awọn ilana. Eyi jẹ ki akoko naa tun dara fun aabo ti ipa iṣelu, ifowosowopo iṣelu, ati idanimọ. Awọn ero ti ibakcdun ni akoko yii ko yẹ ki o jẹ ti owo, ṣugbọn ti orukọ, okiki, ati ọlá";
    private final String firstInBulgarian = "През първите петдесет и два дни от годишния цикъл на всеки бизнес, започвайки с неговия рожден ден и покривайки следващите петдесет и два дни, всеки бизнес ще намери по-голям успех във всички форми на промоция, които търсят или зависят от добрата воля за техния успех и предпочитанията на публиката. Това не е толкова отличен период за реално изграждане на продажби и връщане на парите, колкото е период за осигуряване на одобрение, благосклонност, признание и обща добра воля. Това би бил периодът за получаване на одобрения или високо признание от изтъкнати личности и концерни, които в крайна сметка ще доведат до продажби чрез такива лица, или до даване на широка публичност и реклама на концерна. Освен това е отличен период за широко рекламиране на бизнес, не толкова за директни продажби, колкото за изграждане на престиж и обществено признание. Това е добър период за изпращане на емисари, представители или висши членове на фирмата, за да се срещнат с други видни личности в света на бизнеса и следователно да си осигурят признание и високо благоволение. Поради тази причина е отличен период за работа с правителствени служители, съдии от съда, сенатори или конгресмени, от които желаете предпочитание, специални услуги или приемането на защитни законопроекти или разпоредби. Това прави периода добър и за осигуряване на политическо влияние, политическо сътрудничество и признание. Мисълта за загриженост през този период не трябва да бъде за пари, а за име, репутация и престиж";
    private final String second = "During this period any firm or business of any nature will find that it is a good time to make important changes of a temporary nature in regard to important employees, modifications in business practice, temporary locations, and for trying out short time plans and propositions. On the other hand, it is a very unfavorable period during which to make any new agreements, any new plans of a definite nature, or to enter into any contracts or agreements of any kind unless they are reduced to writing, and properly sealed and signed so as to give them a long time standing. Verbal agreements and arrangements entered into at this time are apt to be cast aside quickly and changed very rapidly or suddenly, and amount to nothing. It is also a good period for the building up of business friendships, and every business firm would do well to take advantage of this period to contact new and prospective customers in a friendly way, for business friendships of a very helpful nature have generally been built up during this period.\n";
    private final String secondInYoruba = "Ni asiko yii eyikeyi ile-iṣẹ tabi iṣowo ti eyikeyi iseda yoo rii pe o jẹ akoko ti o dara lati ṣe awọn ayipada pataki ti iseda igba diẹ ni iyi si awọn oṣiṣẹ pataki, awọn iyipada ninu iṣe iṣowo, awọn ipo igba diẹ, ati fun igbiyanju awọn ero akoko kukuru ati awọn igbero. Ní ọwọ́ kejì ẹ̀wẹ̀, ó jẹ́ àkókò tí kò dára gan-an nínú èyí tí a ti ń ṣe àwọn àdéhùn tuntun èyíkéyìí, àwọn ètò tuntun èyíkéyìí tí ó ní pàtó, tàbí láti wọ inú àwọn àdéhùn tàbí àdéhùn èyíkéyìí èyíkéyìí, àyàfi tí wọ́n bá dín kù sí kíkọ, tí a sì fi èdìdì dì dáradára àti fọwọ́ sí i. ki o le fun wọn ni igba pipẹ duro. Awọn adehun ọrọ-ọrọ ati awọn eto ti a tẹ sinu akoko yii yẹ lati sọ si apakan ni iyara ati yipada ni iyara pupọ tabi lojiji, ati pe ko si nkankan. O tun jẹ akoko ti o dara fun kikọ awọn ọrẹ iṣowo, ati pe gbogbo ile-iṣẹ iṣowo yoo dara lati lo anfani akoko yii lati kan si awọn alabara tuntun ati ti ifojusọna ni ọna ọrẹ, fun awọn ọrẹ iṣowo ti iseda iranlọwọ pupọ ni gbogbogbo ti kọ. soke nigba asiko yi.";

    private final String secondInBulgarian = "През този период всяка фирма или бизнес от всякакво естество ще открие, че е добър момент за извършване на важни промени от временен характер по отношение на важни служители, промени в бизнес практиката, временни местоположения и за изпробване на кратки времеви планове и предложения. От друга страна, това е много неблагоприятен период, през който да се правят нови споразумения, нови планове от определено естество или да се сключват договори или споразумения от всякакъв вид, освен ако не са сведени до писмена форма и правилно подпечатани и подписани така че да им осигури дълго време. Устните споразумения и договорености, сключени по това време, са склонни да бъдат отхвърлени бързо и променени много бързо или внезапно и не водят до нищо. Също така е добър период за изграждане на бизнес приятелства и всяка бизнес фирма би постъпила добре да се възползва от този период, за да се свърже с нови и бъдещи клиенти по приятелски начин, тъй като обикновено се изграждат бизнес приятелства от много полезен характер нагоре през този период.";
    private final String third = "Here we have a period of construction and great energizing power. It is during this period that any business proposition should be pushed to its utmost. Every facility and every means of manufacturing, selling, producing, advertising, promoting, and extending the business should be adopted and utilized to the utmost during this period. It is also a good period for the arrangement of plans for collections, or to send out collectors or letters intended to collect money, but it is not a good period for attempting to fight any issues in court that have to do with the activities of business enemies, business rivals, or business competition. Other legal matters, however, may be pushed at this period, and will generally receive more favorable reaction than at any other period, especially if the matter is one that calls for the expenditure of a great deal of energy and of considerable fighting for the protection of certain issues or rights. On the other hand, every firm and business should watch out for dangerous accidents, disasters, and troubles through enemies, through fires or through sudden explosions of wrath, enmity, or hatred during this period. Manufacturing plants and other propositions should be careful of fires or explosions from fires, gases, and stored-up energies of any kind during this period. It is during this period also that personal enemies of the business will attempt to wreck it or even to injure the character or life of a person connected with a business, if the business has attained any degree of enmity on the part of competitors or others. It is a very good period for dealing with army and navy matters, the military departments of the government, engineering, munitions, machinery, or firms or individuals associated with these.\n";
    private final String thirdInYoruba = "Nibi a ni akoko ikole ati agbara agbara nla. O jẹ lakoko asiko yii pe igbero iṣowo eyikeyi yẹ ki o titari si ipa rẹ. Gbogbo ohun elo ati gbogbo awọn ọna ti iṣelọpọ, tita, iṣelọpọ, ipolowo, igbega, ati faagun iṣowo yẹ ki o gba ati lo si opin ni asiko yii. O tun jẹ akoko ti o dara fun iṣeto awọn eto fun awọn ikojọpọ, tabi lati firanṣẹ awọn agbowọ tabi awọn lẹta ti a pinnu lati gba owo, ṣugbọn kii ṣe akoko ti o dara fun igbiyanju lati ja eyikeyi awọn ọran ni ile-ẹjọ ti o ni ibatan si awọn iṣẹ iṣowo. awọn ọta, awọn abanidije iṣowo, tabi idije iṣowo. Awọn ọrọ ofin miiran, sibẹsibẹ, le ni titari ni akoko yii, ati pe gbogbogbo yoo gba esi ti o dara ju ti akoko eyikeyi miiran, paapaa ti ọrọ naa ba jẹ eyiti o pe fun inawo agbara nla ati ija nla fun aabo. ti awọn oran tabi awọn ẹtọ. Ní ọwọ́ kejì ẹ̀wẹ̀, gbogbo ilé iṣẹ́ àti òwò gbọ́dọ̀ ṣọ́ra fún jàǹbá eléwu, ìjábá, àti wàhálà nípasẹ̀ àwọn ọ̀tá, nípasẹ̀ iná tàbí nípasẹ̀ ìbúgbàù ìbínú, ìṣọ̀tá, tàbí ìkórìíra òjijì ní àkókò yìí. Awọn ohun elo iṣelọpọ ati awọn igbero miiran yẹ ki o ṣọra fun awọn ina tabi awọn bugbamu lati ina, awọn gaasi, ati awọn agbara ti o fipamọ ni iru eyikeyi ni asiko yii. O jẹ ni asiko yii tun pe awọn ọta ti ara ẹni ti iṣowo naa yoo gbiyanju lati bajẹ tabi paapaa lati ṣe ipalara ihuwasi tabi igbesi aye eniyan ti o ni ibatan pẹlu iṣowo kan, ti iṣowo naa ba ti ni alefa ọta eyikeyi ni apakan ti awọn oludije tabi awọn miiran. O jẹ akoko ti o dara pupọ fun ṣiṣe pẹlu awọn ọmọ ogun ati awọn ọran ọgagun, awọn apa ologun ti ijọba, imọ-ẹrọ, awọn ohun ija, ẹrọ, tabi awọn ile-iṣẹ tabi awọn ẹni-kọọkan ti o ni nkan ṣe pẹlu iwọnyi.";

    private final String thirdInBulgarian = "Тук имаме период на изграждане и голяма енергийна сила. Именно през този период всяко бизнес предложение трябва да бъде насочено докрай. Всяко съоръжение и всяко средство за производство, продажба, производство, реклама, популяризиране и разширяване на бизнеса трябва да бъдат възприети и използвани в най-голяма степен през този период. Също така е добър период за организиране на планове за колекции или за изпращане на колекционери или писма, предназначени за събиране на пари, но не е добър период за опити за решаване на проблеми в съда, които са свързани с дейността на бизнеса врагове, бизнес съперници или бизнес конкуренция. Други правни въпроси, обаче, могат да бъдат настоявани в този период и като цяло ще получат по-благоприятна реакция, отколкото във всеки друг период, особено ако въпросът е такъв, който изисква изразходване на много енергия и значителна борба за защита на определени въпроси или права. От друга страна, всяка фирма и бизнес трябва да внимава за опасни произшествия, бедствия и неприятности чрез врагове, чрез пожари или чрез внезапни експлозии на гняв, вражда или омраза през този период. Производствените предприятия и други предложения трябва да внимават за пожари или експлозии от пожари, газове и натрупана енергия от всякакъв вид през този период. През този период също личните врагове на бизнеса ще се опитат да го разрушат или дори да наранят характера или живота на лице, свързано с бизнеса, ако бизнесът е достигнал някаква степен на враждебност от страна на конкуренти или други. Това е много добър период за справяне с въпроси на армията и флота, военните отдели на правителството, инженерство, боеприпаси, машини или фирми или лица, свързани с тях";
    private final String fourth = "This is the period in which any firm or business would do well to enter into its largest campaign of widespread advertising, whether this be nation-wide advertising or the mere solicitation by letter of customers in a limited area. Whatever writing, planning, and scheming of promotion a business firm or individual may want to do in any year of its business, it will be found to be most successful during this period of the business cycle of each year. On the other hand, it is also an excellent period for the drawing up of new contracts, new agreements, papers of incorporation, documents, transfers, and so forth.\n" +
            "\n" +
            "It is an excellent period to deal with newspapermen, diplomats, arbitrators, or others who can use their mentalities or printed or written words to further the interests of the concern. On the other hand, firms must be careful during this period to watch out for deception by word of mouth or writing, for forgeries, and for tricky agreements or plans cleverly presented and which are apt to have a serious reaction in many ways.\n";
    private final String fourthInYoruba = "Eyi ni akoko ninu eyiti eyikeyi ile-iṣẹ tabi iṣowo yoo ṣe daradara lati wọ inu ipolongo rẹ ti o tobi julọ ti ipolowo ibigbogbo, boya eyi jẹ ipolowo jakejado orilẹ-ede tabi ibeere lasan nipasẹ lẹta ti awọn alabara ni agbegbe to lopin. Ohunkohun ti kikọ, igbero, ati igbero igbega ile-iṣẹ iṣowo tabi ẹni kọọkan le fẹ lati ṣe ni eyikeyi ọdun ti iṣowo rẹ, yoo rii pe o ṣaṣeyọri julọ ni asiko yii ti ọna iṣowo ti ọdun kọọkan. Ni apa keji, o tun jẹ akoko ti o dara julọ fun iyaworan awọn adehun tuntun, awọn adehun tuntun, awọn iwe ti isọdọkan, awọn iwe aṣẹ, awọn gbigbe, ati bẹbẹ lọ.\n" +
            "\n" +
            "O jẹ akoko ti o dara julọ lati ba awọn oniroyin, awọn aṣoju ijọba, awọn adajọ, tabi awọn miiran ti o le lo awọn ero inu wọn tabi titẹjade tabi awọn ọrọ kikọ lati tẹsiwaju awọn ire ti ibakcdun naa. Ni apa keji, awọn ile-iṣẹ gbọdọ ṣọra ni akoko yii lati ṣọra fun ẹtan nipasẹ ọrọ ẹnu tabi kikọ, fun awọn ayederu, ati fun awọn adehun ẹtan tabi awọn ero ti a fi ọgbọn gbekalẹ ati eyiti o yẹ lati ni iṣesi pataki ni ọpọlọpọ awọn ọna.";
    private final String fourthInBulgarian = "Това е периодът, в който всяка фирма или бизнес би било добре да започне най-голямата си кампания за широко разпространено рекламиране, независимо дали това е реклама в цялата страна или просто набиране на клиенти чрез писмо в ограничен район. Каквото и писане, планиране и схема за промоция да иска да направи бизнес фирма или физическо лице през която и да е година от своя бизнес, то ще се окаже най-успешно през този период от бизнес цикъла на всяка година. От друга страна, това е и отличен период за изготвяне на нови договори, нови споразумения, документи за учредяване, документи, трансфери и т.н.\n" +
            "\n" +
            "Това е отличен период за работа с вестници, дипломати, арбитри или други, които могат да използват своя манталитет или печатни или писмени думи, за да подкрепят интересите на концерна. От друга страна, фирмите трябва да внимават през този период, за да внимават за измама от уста на уста или писмено, за фалшификации и за хитри споразумения или планове, представени умело и които са склонни да предизвикат сериозна реакция по много начини.";
    private final String fifth = "Here is a period of growth and financial success for any concern or business proposition. This is the period in which to seek investment, or seek to secure credit and extend the tune in which payments must be made or negotiations closed. It is one of the best periods in the business year for selling, and the actual distribution of material on a sales basis, if immediate results and a quick and fair return of money are desired. It is an excellent period in which to collect bad or old debts, and it is an excellent time in which to bring matters into court where the favorable decision desired hangs by a slender thread, for all things being quick and right, this period is favorable to a constructive and just decision. It is an excellent period also for the promotion of the business into foreign lands or distant places or with large concerns that deal in international matters or have international distribution and sales agreements. It seems to be an especially good period for business firms to promote their affairs with railroad, railway, and electric companies, and with all companies and concerns that deal in things that cater to the pleasures and happiness of the public.\n";
    private final String fifthInYoruba = "Eyi ni akoko idagbasoke ati aṣeyọri inawo fun eyikeyi ibakcdun tabi idalaba iṣowo. Eyi ni akoko ti o le wa idoko-owo, tabi wa lati ni aabo kirẹditi ati fa orin dín ninu eyiti awọn sisanwo gbọdọ wa ni pipade tabi awọn idunadura. O jẹ ọkan ninu awọn akoko ti o dara julọ ni ọdun iṣowo fun tita, ati pinpin ohun elo gangan lori ipilẹ tita, ti o ba fẹ awọn abajade lẹsẹkẹsẹ ati ipadabọ ti owo ni iyara. O jẹ akoko ti o tayọ ninu eyiti lati gba awọn gbese buburu tabi atijọ, ati pe o jẹ akoko ti o dara julọ ninu eyiti lati mu awọn ọran lọ si ile-ẹjọ nibiti ipinnu ọjo ti o fẹ kọorí nipasẹ okùn tẹẹrẹ, fun ohun gbogbo ni iyara ati ẹtọ, akoko yii dara julọ. to kan todara ati ki o kan ipinnu. O jẹ akoko ti o dara julọ paapaa fun igbega iṣowo si awọn orilẹ-ede ajeji tabi awọn aaye ti o jinna tabi pẹlu awọn ifiyesi nla ti o ṣe adehun ni awọn ọran kariaye tabi ni pinpin kariaye ati awọn adehun tita. O dabi pe o jẹ akoko ti o dara ni pataki fun awọn ile-iṣẹ iṣowo lati ṣe agbega awọn ọran wọn pẹlu ọkọ oju-irin, ọkọ oju-irin, ati awọn ile-iṣẹ ina, ati pẹlu gbogbo awọn ile-iṣẹ ati awọn ifiyesi ti o ṣe ni awọn nkan ti o pese awọn igbadun ati idunnu ti gbogbo eniyan.";
    private final String fifthInBulgarian = "Това е период на растеж и финансов успех за всяка грижа или бизнес предложение. Това е периодът, в който да търсите инвестиции или да се стремите да осигурите кредит и да удължите периода, в който трябва да се извършат плащанията или да се приключат преговорите. Това е един от най-добрите периоди в стопанската година за продажба и действителното разпределение на материалите на база продажби, ако се искат незабавни резултати и бързо и справедливо възвръщане на парите. Това е отличен период за събиране на лоши или стари дългове и е отлично време за внасяне на въпроси в съда, където желаното благоприятно решение виси на тънка нишка, тъй като всичко е бързо и правилно, този период е благоприятен до градивно и справедливо решение. Това е отличен период и за насърчаване на бизнеса в чужди земи или отдалечени места или с големи концерни, които се занимават с международни въпроси или имат международни споразумения за разпространение и продажба. Изглежда, че е особено добър период за бизнес фирмите да популяризират своите дела с железопътни, железопътни и електрически компании, както и с всички компании и концерни, които се занимават с неща, които се грижат за удоволствията и щастието на обществото.";
    private final String sixth = "This is the period in each year when every business should relax its activities if it finds it necessary to relax at all, and should plan its periods for the vacation or absence of any of its important directors or operators. It is also an excellent period for the promotion of certain branches of business such as those that deal with the art world, or with music, poetry, sculpturing, artists' materials, women's clothing, or articles of adornment, beauty preparations, high grade shoes, hosiery, evening wraps, hats, luxurious automobiles, oriental rugs, antique furniture, fine books, expensive musical instruments, concerts, operas, and other things representing the luxuries, refinements, and clean and wholesome pleasures of life. Therefore, it is well to push the sale of things of this nature during this period, or to promote good will or interest among persons who are associated with such lines of business. This is an excellent period for the heads of a concern or the individual owner of any kind of business to make the acquaintance of his customers, and to make such intimate contacts with persons as may be helpful to the business or the individuals of the business in the near future. It is also a good period for the collection of money, the buying of stocks and bonds, or the promotion of the finances of the company through investment in conservative stocks of other concerns. Therefore, it would be an excellent period for the bringing about of partnerships, monopolistic corporations and the formation of subsidiary associations and alliances of a similar nature.";
    private final String sixthInYoruba = "Eyi ni akoko ni ọdun kọọkan nigbati gbogbo iṣowo yẹ ki o sinmi awọn iṣẹ rẹ ti o ba rii pe o jẹ dandan lati sinmi ni gbogbo, ati pe o yẹ ki o gbero awọn akoko rẹ fun isinmi tabi isansa ti eyikeyi awọn oludari pataki tabi awọn oniṣẹ. O tun jẹ akoko ti o dara julọ fun igbega awọn ẹka kan ti iṣowo gẹgẹbi awọn ti o niiṣe pẹlu aye aworan, tabi pẹlu orin, ewi, aworan aworan, awọn ohun elo awọn oṣere, awọn aṣọ obirin, tabi awọn ohun ọṣọ, awọn igbaradi ẹwa, awọn bata bata giga. , hosiery, irọlẹ, awọn fila, awọn ọkọ ayọkẹlẹ adun, awọn aṣọ atẹrin ila-oorun, awọn ohun-ọṣọ atijọ, awọn iwe didara, awọn ohun elo orin ti o niyelori, awọn ere orin, awọn opera, ati awọn ohun miiran ti o nsoju awọn igbadun, awọn atunṣe, ati awọn igbadun ti o mọ ati ti o dara ti igbesi aye. Nitorinaa, o dara lati Titari tita awọn nkan ti ẹda yii ni asiko yii, tabi lati ṣe agbega ifẹ tabi anfani laarin awọn eniyan ti o ni nkan ṣe pẹlu iru awọn laini iṣowo. Eyi jẹ akoko ti o tayọ fun awọn olori ti ibakcdun tabi oniwun kọọkan ti eyikeyi iru iṣowo lati ṣe ojulumọ awọn alabara rẹ, ati lati ṣe iru awọn ibatan timotimo pẹlu eniyan bi o ṣe le ṣe iranlọwọ fun iṣowo tabi awọn ẹni kọọkan ti iṣowo ni awọn sunmọ iwaju. O tun jẹ akoko ti o dara fun gbigba owo, rira awọn ọja ati awọn iwe ifowopamosi, tabi igbega awọn inawo ti ile-iṣẹ nipasẹ idoko-owo ni awọn akojopo Konsafetifu ti awọn ifiyesi miiran. Nitorinaa, yoo jẹ akoko ti o tayọ fun mimuwa awọn ajọṣepọ, awọn ile-iṣẹ monopolistic ati didasilẹ awọn ẹgbẹ oniranlọwọ ati awọn ajọṣepọ ti ẹda ti o jọra.";
    private final String sixthInBulgarian = "Това е периодът във всяка година, когато всеки бизнес трябва да отпусне дейността си, ако изобщо намери за необходимо да отпусне и да планира периодите си за отпуск или отсъствие на някой от важните си директори или оператори. Също така е отличен период за насърчаване на определени клонове на бизнеса като тези, които се занимават със света на изкуството или с музика, поезия, скулптура, материали за художници, дамско облекло или предмети за украса, козметични продукти, висококачествени обувки , чорапогащи, вечерни тоалети, шапки, луксозни автомобили, ориенталски килими, антични мебели, изискани книги, скъпи музикални инструменти, концерти, опери и други неща, представящи лукса, изтънчеността и чистите и здравословни удоволствия от живота. Следователно е добре да се насърчава продажбата на неща от този характер през този период или да се насърчава добрата воля или интерес сред лица, които са свързани с такива направления на дейност. Това е отличен период за ръководителите на концерн или отделните собственици на всякакъв вид бизнес да осъществят запознанства с клиентите си и да осъществят такива интимни контакти с лица, които могат да бъдат полезни за бизнеса или лицата от бизнеса в близкото бъдеще. Също така е добър период за събиране на пари, закупуване на акции и облигации или насърчаване на финансите на компанията чрез инвестиции в консервативни акции от други интереси. Следователно това би бил отличен период за създаване на партньорства, монополни корпорации и формиране на дъщерни асоциации и съюзи от подобен характер.";
    private final String seventh = "Here we have the reconstruction period for all business propositions, and during these last fifty-two days before the birthday of the concern or business, great care must be taken not to start any new line of activity or to go too heavily into advertising that is intended to build up a new department or a new phase of the business, or to do otherwise than cooperate with the Cosmic tendencies to reconstruct. Since\n" +
            "it is the period during which changes of a tearing down nature must be expected, it is a wrong period in which to plan to do reconstruction without the preliminary stage of tearing down.\n" +
            "In other words, during this period no expansion must be expected unless it is associated in some way with a breaking down or tearing down process as a part of the reconstruction. Since some form of breaking down and change is very apt to take place during these fifty-two days, every business concern or individual should see that any contemplated changes or tearing down processes that have been in mind are brought to issue during this time, and therefore permitted to expend themselves or manifest themselves while such a period is favorable. Certainly no new alliances, affiliations, partnerships, or agreements, contracts, or offers of agreement or contract should be made during this period. It is an excellent time to consult with persons in retirement, or who have been in business and have retired, or with judges,\n" +
            "referees, or advisers of any kind. All acts must be guarded with a conservative attitude, and extreme caution and providence manifested in every line of activity. Great diplomacy must be shown n every act, and every business should take advantage of this period to conserve its activities, hold steady to its line of progress, and not allow anything of a radical nature in either advertising, selling, buying, or planning to occur.\n";
    private final String seventhInYoruba = "Nibi a ni akoko atunkọ fun gbogbo awọn iṣeduro iṣowo, ati ni awọn ọjọ mejilelọgọta ti o kẹhin wọnyi ṣaaju ọjọ-ibi ti ibakcdun tabi iṣowo, a gbọdọ ṣe akiyesi nla lati maṣe bẹrẹ laini iṣẹ tuntun tabi lati lọ lọpọlọpọ sinu ipolowo ti o jẹ. ti pinnu lati kọ ẹka tuntun tabi ipele tuntun ti iṣowo naa, tabi lati ṣe bibẹẹkọ ju ifọwọsowọpọ pẹlu awọn iṣesi Agbaye lati tun ṣe. Níwọ̀n bí ó ti jẹ́ pé àkókò tí a gbọ́dọ̀ retí àwọn ìyípadà ti yíya lulẹ̀ ìṣẹ̀dá, ó jẹ́ àkókò tí kò tọ́ nínú èyí tí a ti ṣètò láti ṣe àtúnkọ́ láìsí ìpele àkọ́kọ́ ti wó lulẹ̀.\n" +
            "\n" +
            "Ni awọn ọrọ miiran, lakoko asiko yii ko si imugboroosi gbọdọ nireti ayafi ti o ba ni nkan ṣe ni ọna kan pẹlu fifọ lulẹ tabi ilana fifọ bi apakan ti atunkọ. Niwọn igba ti diẹ ninu iru fifọ ati iyipada jẹ pipe lati waye lakoko awọn ọjọ mejilelaadọta wọnyi, gbogbo ibakcdun iṣowo tabi ẹni kọọkan yẹ ki o rii pe eyikeyi awọn ayipada ti o ronu tabi fifọ awọn ilana ti o ti wa ni lokan ni a mu wa si atejade ni akoko yii, ati nitorinaa gba laaye lati lo ara wọn tabi ṣafihan ara wọn lakoko ti iru akoko bẹẹ jẹ ọjo. Dajudaju ko si awọn ajọṣepọ tuntun, awọn ibatan, awọn ajọṣepọ, tabi awọn adehun, awọn adehun, tabi awọn ipese ti adehun tabi adehun ti o yẹ ki o ṣe lakoko yii. O jẹ akoko ti o dara julọ lati kan si alagbawo pẹlu awọn eniyan ti o wa ni ifẹhinti lẹnu iṣẹ, tabi ti o ti wa ni iṣowo ti wọn ti fẹyìntì, tabi pẹlu awọn onidajọ, awọn adajọ, tabi awọn oludamọran iru eyikeyi. Gbogbo awọn iṣe gbọdọ wa ni aabo pẹlu ihuwasi Konsafetifu, ati iṣọra pupọ ati ipese ti o farahan ni gbogbo laini iṣẹ. diplomacy nla gbọdọ wa ni afihan ni gbogbo iṣe, ati pe gbogbo iṣowo yẹ ki o lo anfani akoko yii lati ṣe itọju awọn iṣẹ rẹ, duro ṣinṣin si laini ilọsiwaju rẹ, ati ki o ma ṣe gba laaye ohunkohun ti iseda ti ipilẹṣẹ ni boya ipolongo, tita, rira, tabi ṣiṣero si ṣẹlẹ.";

    private final String seventhInBulgarian = "Nibi a ni akoko atunkọ fun gbogbo awọn iṣeduro iṣowo, ati ni awọn ọjọ mejilelọgọta ti o kẹhin wọnyi ṣaaju ọjọ-ibi ti ibakcdun tabi iṣowo, a gbọdọ ṣe akiyesi nla lati maṣe bẹrẹ laini iṣẹ tuntun tabi lati lọ lọpọlọpọ sinu ipolowo ti o jẹ. ti pinnu lati kọ ẹka tuntun tabi ipele tuntun ti iṣowo naa, tabi lati ṣe bibẹẹkọ ju ifọwọsowọpọ pẹlu awọn iṣesi Agbaye lati tun ṣe. Níwọ̀n bí ó ti jẹ́ pé àkókò tí a gbọ́dọ̀ retí àwọn ìyípadà ti yíya lulẹ̀ ìṣẹ̀dá, ó jẹ́ àkókò tí kò tọ́ nínú èyí tí a ti ṣètò láti ṣe àtúnkọ́ láìsí ìpele àkọ́kọ́ ti wó lulẹ̀.\n" +
            "\n" +
            "Ni awọn ọrọ miiran, lakoko asiko yii ko si imugboroosi gbọdọ nireti ayafi ti o ba ni nkan ṣe ni ọna kan pẹlu fifọ lulẹ tabi ilana fifọ bi apakan ti atunkọ. Niwọn igba ti diẹ ninu iru fifọ ati iyipada jẹ pipe lati waye lakoko awọn ọjọ mejilelaadọta wọnyi, gbogbo ibakcdun iṣowo tabi ẹni kọọkan yẹ ki o rii pe eyikeyi awọn ayipada ti o ronu tabi fifọ awọn ilana ti o ti wa ni lokan ni a mu wa si atejade ni akoko yii, ati nitorinaa gba laaye lati lo ara wọn tabi ṣafihan ara wọn lakoko ti iru akoko bẹẹ jẹ ọjo. Dajudaju ko si awọn ajọṣepọ tuntun, awọn ibatan, awọn ajọṣepọ, tabi awọn adehun, awọn adehun, tabi awọn ipese ti adehun tabi adehun ti o yẹ ki o ṣe lakoko yii. O jẹ akoko ti o dara julọ lati kan si alagbawo pẹlu awọn eniyan ti o wa ni ifẹhinti lẹnu iṣẹ, tabi ti o ti wa ni iṣowo ti wọn ti fẹyìntì, tabi pẹlu awọn onidajọ, awọn adajọ, tabi awọn oludamọran iru eyikeyi. Gbogbo awọn iṣe gbọdọ wa ni aabo pẹlu ihuwasi Konsafetifu, ati iṣọra pupọ ati ipese ti o farahan ni gbogbo laini iṣẹ. diplomacy nla gbọdọ wa ni afihan ni gbogbo iṣe, ati pe gbogbo iṣowo yẹ ki o lo anfani akoko yii lati ṣe itọju awọn iṣẹ rẹ, duro ṣinṣin si laini ilọsiwaju rẹ, ati ki o ma ṣe gba laaye ohunkohun ti iseda ti ipilẹṣẹ ni boya ipolongo, tita, rira, tabi ṣiṣero si ṣẹlẹ.";
}
